version: "3"
services:
  
  #ecommerce-service block
  ecommerce-app:
  
    build: ${ECOMMERCE_SERVICE_PATH}/Docker/app/.
  
    container_name: ${ECOMMERCE_SERVICE_NAME}
  
    env_file:
      - ${ECOMMERCE_SERVICE_PATH}/Docker/app/.env
      - .env
    
    environment:
      - FIRESTORE_EMULATOR_HOST=${ECOMMERCE_FIRESTORE_NAME}:8080
      - FIRESTORE_PROJECT_ID=${ECOMMERCE_FIRESTORE_NAME}

    command: ["npm", "run", "dev"]
  
    volumes:
      - ${ECOMMERCE_SERVICE_PATH}/src:/app/src
      - ${ECOMMERCE_SERVICE_PATH}/tests:/app/tests
      - ${ECOMMERCE_SERVICE_PATH}/Docker/database/firestore-account:/app/firestore-account
      
    ports:
      - ${ECOMMERCE_APP_PORT}:8080
    
    depends_on:
      - ecommerce-firestore
  
  ecommerce-firestore:

    container_name: ${ECOMMERCE_FIRESTORE_NAME}

    image: mtlynch/firestore-emulator

    environment:
      FIRESTORE_PROJECT_ID: ${ECOMMERCE_FIRESTORE_NAME}
    
  #delivery-service block
  delivery-app:
  
    build: ${DELIVERY_SERVICE_PATH}/Docker/app/.
  
    container_name: ${DELIVERY_SERVICE_NAME}
  
    env_file:
      - ${DELIVERY_SERVICE_PATH}/Docker/app/.env
      - .env
    
    environment:
      - FIRESTORE_EMULATOR_HOST=${DELIVERY_FIRESTORE_NAME}:8080
      - FIRESTORE_PROJECT_ID=${DELIVERY_FIRESTORE_NAME}

    command: ["npm", "run", "dev"]
  
    volumes:
      - ${DELIVERY_SERVICE_PATH}/src:/app/src
      - ${DELIVERY_SERVICE_PATH}/tests:/app/tests
      - ${DELIVERY_SERVICE_PATH}/Docker/database/firestore-account:/app/firestore-account
      
    ports:
      - ${DELIVERY_APP_PORT}:8080
    
    depends_on:
      - delivery-firestore
  
  delivery-firestore:

    container_name: ${DELIVERY_FIRESTORE_NAME}

    image: mtlynch/firestore-emulator

    environment:
      FIRESTORE_PROJECT_ID: ${DELIVERY_FIRESTORE_NAME}
